#!/bin/sh
#
# If you wish to run this script as not a superuser
# you should have program sudo installed and properly
# configured.
#
# If you run this script as root, or if you have /sbin/insmod setuid root,
# comment out the next line
# SUDO=sudo
#
LINUX_VERSION=`uname -r`
sync;sync

#change to NTSC or SECAM or PAL
norm=UNKNOWN

# Unload everything
$SUDO /sbin/rmmod dc10 > /dev/null 2>&1     # Just in case if old driver was loaded
$SUDO /sbin/rmmod zoran > /dev/null 2>&1
# If you don't have DC10 or DC10plus card comment out next three lines
$SUDO /sbin/rmmod adv7175 > /dev/null 2>&1
$SUDO /sbin/rmmod saa7110 > /dev/null 2>&1
$SUDO /sbin/rmmod zr36060 > /dev/null 2>&1
# If you don't have BUZ card comment out next three lines
$SUDO /sbin/rmmod saa7111 > /dev/null 2>&1
$SUDO /sbin/rmmod saa7185 > /dev/null 2>&1
$SUDO /sbin/rmmod zr36060 > /dev/null 2>&1
# If you don't have LML33 card comment out next three lines
$SUDO /sbin/rmmod bt819 > /dev/null 2>&1
$SUDO /sbin/rmmod bt856 > /dev/null 2>&1
$SUDO /sbin/rmmod zr36060 > /dev/null 2>&1
# If you don't have a dc30/dc30plus, you don't need the next four lines
$SUDO /sbin/rmmod adv7175 > /dev/null 2>&1
$SUDO /sbin/rmmod vpx3220 > /dev/null 2>&1
$SUDO /sbin/rmmod zr36016 > /dev/null 2>&1
$SUDO /sbin/rmmod zr36050 > /dev/null 2>&1

$SUDO /sbin/rmmod videocodec > /dev/null 2>&1

$SUDO /sbin/rmmod i2c-old > /dev/null 2>&1
$SUDO /sbin/rmmod i2c-algo-bit > /dev/null 2>&1
$SUDO /sbin/rmmod i2c-core > /dev/null 2>&1
$SUDO /sbin/rmmod videodev > /dev/null 2>&1

# Load driver

sync;sync
$SUDO /sbin/insmod videodev

# I2COPTS="scan=1"

$SUDO /sbin/insmod i2c-core $I2CCOREOPTS
$SUDO /sbin/insmod i2c-algo-bit $I2CALGOBITOPTS

$SUDO /sbin/insmod ./videocodec.o

incompat=""
cards=""

while [ "$1" != "" ]
do
    case "$1" in
    
        'dc10'|'dc10plus')
            $SUDO /sbin/insmod ./saa7110.o
            $SUDO /sbin/insmod ./adv7175.o
            $SUDO /sbin/insmod ./zr36060.o
            cards="$cards $1"
            ;;
        'lml33')
            if [ "$incompat" = "buz" ]
            then
                echo "Using of Buz and LML33 cards in the same system is not yet supported"
                echo "Installation aborted."
                exit 1
            fi
            $SUDO /sbin/insmod ./bt819.o
            $SUDO /sbin/insmod ./bt856.o
            $SUDO /sbin/insmod ./zr36060.o
            cards="$cards $1"
            incompat="lml33"
            ;;
        'buz')
            if [ "$incompat" = "lml33" ]
            then
                echo "Using of Buz and LML33 cards in the same system is not yet supported"
                echo "Installation aborted."
                exit 1
            fi
            $SUDO /sbin/insmod ./saa7111.o
            $SUDO /sbin/insmod ./saa7185.o
            $SUDO /sbin/insmod ./zr36060.o
            cards="$cards $1"
            incompat="buz"
            ;;
        'dc30'|'dc30plus')
            $SUDO /sbin/insmod ./vpx3220.o
            #$SUDO /sbin/insmod ./tea6415.o
            echo "playback disabled for $1 since the chipset (tea6415) specs are unknown"
            $SUDO /sbin/insmod ./zr36016.o
            $SUDO /sbin/insmod ./zr36050.o
            cards="$cards $1"
            ;;
        *)
            ;;
    esac
    shift
done

if [ "$cards" = "" ]
then
    echo "No cards were specified. Installation aborted."
    exit 1
fi

sync;sync
sleep 1
# For information about options, please, check file README.
# If you have PAL signal in you country, change to default_norm=0 in the next line
normnum=0
case "$norm" in
    'PAL')
        normnum=0
        ;;
    'NTSC')
        normnum=1
        ;;
    'SECAM')
        normnum=2
        ;;
    *)
        echo "No norm given - please edit this script!"
        exit 1
        ;;
esac
$SUDO /sbin/insmod ./zoran.o default_norm=$normnum lock_norm=0 pass_through=0 lml33dpath=1 # v4l_bufsize=1280
sync;sync
echo "Drivers for '$cards' with norm '$norm' loaded"
