int average_coeff(unsigned int,unsigned int,unsigned int *);
void print_usage(char *argv[]);
void handle_args_global (int argc, char *argv[]);
void handle_args_dependent (int argc, char *argv[]);
int main (int argc, char *argv[]);
int average_coeff (unsigned int input_length, unsigned int output_length,unsigned int *coeff);
int average_Y (uint8_t * input, uint8_t * output, unsigned int *height_coeff,unsigned int *width_coeff);
int average_Y_specific (uint8_t * input, uint8_t * output, unsigned int *height_coeff,unsigned int *width_coeff);
int average_UV (uint8_t * input, uint8_t * output, unsigned int *height_coeff,unsigned int *width_coeff);
int average_UV_specific (uint8_t * input, uint8_t * output, unsigned int *height_coeff,unsigned int *width_coeff);
unsigned int pgcd (unsigned int num1, unsigned int num2);
